version: "3.1"
services:
  server:
    container_name: server
    image: server:latest
    ports:
      - 8888:8888
    networks:
      - sc1

  discovery:
    container_name: discovery
    image: discovery:latest
    ports:
      - 8083:8083
    links:
      - server
    depends_on:
      - server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:8888/login"]
    networks:
      - sc1

  gateway:
    container_name: gateway
    image: gateway:latest
    ports:
      - 8084:8084
    links:
      - server
      - discovery
      - redis
    depends_on:
      - server
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:8888/login"]
    networks:
      - sc1

  client:
    container_name: client
    image: client:latest
    ports:
      - 8082:8082
    links:
      - server
      - discovery
    depends_on:
      - server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:8888/login"]
    networks:
      - sc1

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - sc1

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cloud
    volumes:
      - /home/kuba/Desktop/projects/SpringCloud/db:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - sc1

  adminer:
   image: adminer
   container_name: adminer
   ports:
      - 5000:8080
   networks:
      - sc1

networks:
  sc1:
    driver: bridge
